### ISSUE TITLE
Better error in `gen_agg` if attribute is not found

### ISSUE THREAD

**Issue by engeir** [engeir/cesm-helper-scripts#4]
In the `gen_agg` script, check at an earlier time if attributes are in the netCDF files, and catch the error with a nicer print instead of having the whole script crash:

```console
➜ een023 @ SSH:c8-8 in /cluster/projects/nn9817k/cesm/archive/e_BWmaHIST-ens1/atm/hist via 🐍 v3.8.2 (p3) took 6s (09:06:47)
➜  gen_agg -i "e_BWmaHIST-ens1.cam.h7.185*" -a AEROD_v TREFHT
Saving to ./AEROD_v20220211.nc
Saving to ./TREFHT20220211.nc
Creating aggregated dataset...
Finished creating aggregated dataset...
Start creating file for attr AEROD_v
Traceback (most recent call last):
  File "/cluster/home/een023/.local/bin/gen_agg", line 123, in <module>                                          )
    ds = getattr(dataset, a)
  File "/cluster/home/een023/.virtualenvs/p3/lib/python3.8/site-packages/xarray/core/common.py", line 228, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'AEROD_v'
```

**Comment by engeir** [comment]
Resolved by commit fcae8cae110c6d9818a4c0614ba43e8e5ebea3b2.
